apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-depl
  template:
    metadata:
      labels:
        app: query-depl
    spec:
      containers:
      - name: query-depl
        image: rudy5/query
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
  - port: 2001
    targetPort: 2001
